from fastapi import APIRouter
from app.api.v1.endpoints import (
    ai_conversations,
    ai_contextual_analysis,
    ai_context,
    ai_assistant,
    alerts,
    arbitrage,
    auth,
    automation,
    copy_trading,
    exchange_accounts,
    exchange_connections,
    exchange_trading,
    health,
    market_scanner,
    notification_preferences,
    portfolios,
    risk_management,
    strategy_templates,
    trading_bot_backtest,
    trading_bot_history,
    trading_bots,
    users,
    watchlists,
)
api_router = APIRouter()
api_router.include_router(health.router)
api_router.include_router(auth.router)
api_router.include_router(users.router)
api_router.include_router(portfolios.router)
api_router.include_router(watchlists.router)
api_router.include_router(alerts.router)
api_router.include_router(arbitrage.router)
api_router.include_router(
    notification_preferences.router
)
api_router.include_router(
    exchange_accounts.router
)
api_router.include_router(
    exchange_connections.router
)
api_router.include_router(
    exchange_trading.router
)
api_router.include_router(
    risk_management.router
)
api_router.include_router(
    trading_bot_backtest.router
)
api_router.include_router(
    trading_bot_history.router
)
api_router.include_router(
    trading_bots.router
)
api_router.include_router(
    strategy_templates.router
)
api_router.include_router(
    copy_trading.router
)
api_router.include_router(
    market_scanner.router
)
api_router.include_router(
    automation.router
)
api_router.include_router(ai_assistant.router)
api_router.include_router(ai_context.router)
api_router.include_router(ai_contextual_analysis.router)
api_router.include_router(ai_conversations.router)
