"""create trading bots table
Revision ID: 12a0b1c2d3e4
Revises: f11c0a1b2c3d
Create Date: 2026-07-21 12:00:00.000000
"""
from typing import (
    Sequence,
    Union,
)
from alembic import (
    op,
)
import sqlalchemy as sa
revision: str = "12a0b1c2d3e4"
down_revision: Union[
    str,
    Sequence[str],
    None,
] = "f11c0a1b2c3d"
branch_labels: Union[
    str,
    Sequence[str],
    None,
] = None
depends_on: Union[
    str,
    Sequence[str],
    None,
] = None
def upgrade() -> None:
    op.create_table(
        "trading_bots",
        sa.Column(
            "id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "user_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "exchange_account_id",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "name",
            sa.String(length=150),
            nullable=False,
        ),
        sa.Column(
            "description",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "strategy_type",
            sa.String(length=50),
            nullable=False,
        ),
        sa.Column(
            "symbol",
            sa.String(length=30),
            nullable=False,
        ),
        sa.Column(
            "category",
            sa.String(length=20),
            server_default=sa.text(
                "'linear'"
            ),
            nullable=False,
        ),
        sa.Column(
            "timeframe",
            sa.String(length=20),
            server_default=sa.text(
                "'5m'"
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            server_default=sa.text(
                "'DRAFT'"
            ),
            nullable=False,
        ),
        sa.Column(
            "paper_trading",
            sa.Boolean(),
            server_default=sa.text("1"),
            nullable=False,
        ),
        sa.Column(
            "dry_run",
            sa.Boolean(),
            server_default=sa.text("1"),
            nullable=False,
        ),
        sa.Column(
            "risk_per_trade_percent",
            sa.Float(),
            server_default=sa.text(
                "1.0"
            ),
            nullable=False,
        ),
        sa.Column(
            "max_position_value_usd",
            sa.Float(),
            server_default=sa.text(
                "25.0"
            ),
            nullable=False,
        ),
        sa.Column(
            "max_daily_loss_percent",
            sa.Float(),
            server_default=sa.text(
                "3.0"
            ),
            nullable=False,
        ),
        sa.Column(
            "max_drawdown_percent",
            sa.Float(),
            server_default=sa.text(
                "10.0"
            ),
            nullable=False,
        ),
        sa.Column(
            "stop_loss_percent",
            sa.Float(),
            nullable=True,
        ),
        sa.Column(
            "take_profit_percent",
            sa.Float(),
            nullable=True,
        ),
        sa.Column(
            "strategy_config",
            sa.JSON(),
            server_default=sa.text(
                "'{}'"
            ),
            nullable=False,
        ),
        sa.Column(
            "last_error",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "stopped_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "last_run_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text(
                "(CURRENT_TIMESTAMP)"
            ),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text(
                "(CURRENT_TIMESTAMP)"
            ),
            nullable=False,
        ),
        sa.CheckConstraint(
            "paper_trading OR dry_run",
            name=(
                "ck_trading_bots_"
                "execution_safety"
            ),
        ),
        sa.CheckConstraint(
            (
                "risk_per_trade_percent "
                "> 0"
            ),
            name=(
                "ck_trading_bots_"
                "risk_positive"
            ),
        ),
        sa.CheckConstraint(
            (
                "max_position_value_usd "
                "> 0"
            ),
            name=(
                "ck_trading_bots_"
                "position_value_positive"
            ),
        ),
        sa.CheckConstraint(
            (
                "risk_per_trade_percent "
                "<= max_daily_loss_percent"
            ),
            name=(
                "ck_trading_bots_"
                "risk_daily_loss"
            ),
        ),
        sa.CheckConstraint(
            (
                "max_daily_loss_percent "
                "<= max_drawdown_percent"
            ),
            name=(
                "ck_trading_bots_"
                "daily_loss_drawdown"
            ),
        ),
        sa.CheckConstraint(
            (
                "stop_loss_percent IS NULL "
                "OR stop_loss_percent > 0"
            ),
            name=(
                "ck_trading_bots_"
                "stop_loss_positive"
            ),
        ),
        sa.CheckConstraint(
            (
                "take_profit_percent IS NULL "
                "OR take_profit_percent > 0"
            ),
            name=(
                "ck_trading_bots_"
                "take_profit_positive"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["exchange_account_id"],
            ["exchange_accounts.id"],
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id",
            "name",
            name=(
                "uq_trading_bots_"
                "user_name"
            ),
        ),
    )
    op.create_index(
        op.f(
            "ix_trading_bots_id"
        ),
        "trading_bots",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f(
            "ix_trading_bots_user_id"
        ),
        "trading_bots",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f(
            "ix_trading_bots_"
            "exchange_account_id"
        ),
        "trading_bots",
        ["exchange_account_id"],
        unique=False,
    )
    op.create_index(
        op.f(
            "ix_trading_bots_"
            "strategy_type"
        ),
        "trading_bots",
        ["strategy_type"],
        unique=False,
    )
    op.create_index(
        op.f(
            "ix_trading_bots_symbol"
        ),
        "trading_bots",
        ["symbol"],
        unique=False,
    )
    op.create_index(
        op.f(
            "ix_trading_bots_timeframe"
        ),
        "trading_bots",
        ["timeframe"],
        unique=False,
    )
    op.create_index(
        op.f(
            "ix_trading_bots_status"
        ),
        "trading_bots",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f(
            "ix_trading_bots_updated_at"
        ),
        "trading_bots",
        ["updated_at"],
        unique=False,
    )
    op.create_index(
        "ix_trading_bots_user_status",
        "trading_bots",
        [
            "user_id",
            "status",
        ],
        unique=False,
    )
    op.create_index(
        "ix_trading_bots_user_updated",
        "trading_bots",
        [
            "user_id",
            "updated_at",
        ],
        unique=False,
    )
def downgrade() -> None:
    op.drop_index(
        "ix_trading_bots_user_updated",
        table_name="trading_bots",
    )
    op.drop_index(
        "ix_trading_bots_user_status",
        table_name="trading_bots",
    )
    op.drop_index(
        op.f(
            "ix_trading_bots_updated_at"
        ),
        table_name="trading_bots",
    )
    op.drop_index(
        op.f(
            "ix_trading_bots_status"
        ),
        table_name="trading_bots",
    )
    op.drop_index(
        op.f(
            "ix_trading_bots_timeframe"
        ),
        table_name="trading_bots",
    )
    op.drop_index(
        op.f(
            "ix_trading_bots_symbol"
        ),
        table_name="trading_bots",
    )
    op.drop_index(
        op.f(
            "ix_trading_bots_"
            "strategy_type"
        ),
        table_name="trading_bots",
    )
    op.drop_index(
        op.f(
            "ix_trading_bots_"
            "exchange_account_id"
        ),
        table_name="trading_bots",
    )
    op.drop_index(
        op.f(
            "ix_trading_bots_user_id"
        ),
        table_name="trading_bots",
    )
    op.drop_index(
        op.f(
            "ix_trading_bots_id"
        ),
        table_name="trading_bots",
    )
    op.drop_table("trading_bots")
