"""create paper trading tables
Revision ID: 12f0a1b2c3d4
Revises: 12a0b1c2d3e4
Create Date: 2026-07-21
"""
from collections.abc import (
    Sequence,
)
from alembic import op
import sqlalchemy as sa
revision: str = "12f0a1b2c3d4"
down_revision: str | None = (
    "12a0b1c2d3e4"
)
branch_labels: (
    str
    | Sequence[str]
    | None
) = None
depends_on: (
    str
    | Sequence[str]
    | None
) = None
def upgrade() -> None:
    op.create_table(
        "paper_trading_accounts",
        sa.Column(
            "id",
            sa.Integer(),
            primary_key=True,
        ),
        sa.Column(
            "user_id",
            sa.Integer(),
            sa.ForeignKey(
                "users.id",
                ondelete="CASCADE",
            ),
            nullable=False,
        ),
        sa.Column(
            "trading_bot_id",
            sa.Integer(),
            sa.ForeignKey(
                "trading_bots.id",
                ondelete="CASCADE",
            ),
            nullable=False,
        ),
        sa.Column(
            "currency",
            sa.String(length=20),
            nullable=False,
            server_default="USDT",
        ),
        sa.Column(
            "initial_balance_usd",
            sa.Float(),
            nullable=False,
            server_default=sa.text("10000"),
        ),
        sa.Column(
            "cash_balance_usd",
            sa.Float(),
            nullable=False,
            server_default=sa.text("10000"),
        ),
        sa.Column(
            "reserved_balance_usd",
            sa.Float(),
            nullable=False,
            server_default=sa.text("0"),
        ),
        sa.Column(
            "equity_usd",
            sa.Float(),
            nullable=False,
            server_default=sa.text("10000"),
        ),
        sa.Column(
            "realized_pnl_usd",
            sa.Float(),
            nullable=False,
            server_default=sa.text("0"),
        ),
        sa.Column(
            "unrealized_pnl_usd",
            sa.Float(),
            nullable=False,
            server_default=sa.text("0"),
        ),
        sa.Column(
            "total_fees_usd",
            sa.Float(),
            nullable=False,
            server_default=sa.text("0"),
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=False,
            server_default="ACTIVE",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.CheckConstraint(
            "initial_balance_usd > 0",
            name=(
                "ck_paper_accounts_"
                "initial_positive"
            ),
        ),
        sa.CheckConstraint(
            "cash_balance_usd >= 0",
            name=(
                "ck_paper_accounts_"
                "cash_nonnegative"
            ),
        ),
        sa.CheckConstraint(
            "reserved_balance_usd >= 0",
            name=(
                "ck_paper_accounts_"
                "reserved_nonnegative"
            ),
        ),
        sa.CheckConstraint(
            "total_fees_usd >= 0",
            name=(
                "ck_paper_accounts_"
                "fees_nonnegative"
            ),
        ),
        sa.UniqueConstraint(
            "trading_bot_id",
            name=(
                "uq_paper_accounts_"
                "trading_bot"
            ),
        ),
    )
    op.create_index(
        "ix_paper_accounts_user_status",
        "paper_trading_accounts",
        [
            "user_id",
            "status",
        ],
    )
    op.create_table(
        "paper_trading_positions",
        sa.Column(
            "id",
            sa.Integer(),
            primary_key=True,
        ),
        sa.Column(
            "user_id",
            sa.Integer(),
            sa.ForeignKey(
                "users.id",
                ondelete="CASCADE",
            ),
            nullable=False,
        ),
        sa.Column(
            "trading_bot_id",
            sa.Integer(),
            sa.ForeignKey(
                "trading_bots.id",
                ondelete="CASCADE",
            ),
            nullable=False,
        ),
        sa.Column(
            "paper_account_id",
            sa.Integer(),
            sa.ForeignKey(
                "paper_trading_accounts.id",
                ondelete="CASCADE",
            ),
            nullable=False,
        ),
        sa.Column(
            "symbol",
            sa.String(length=30),
            nullable=False,
        ),
        sa.Column(
            "category",
            sa.String(length=20),
            nullable=False,
        ),
        sa.Column(
            "side",
            sa.String(length=10),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=False,
            server_default="OPEN",
        ),
        sa.Column(
            "quantity",
            sa.Float(),
            nullable=False,
        ),
        sa.Column(
            "average_entry_price",
            sa.Float(),
            nullable=False,
        ),
        sa.Column(
            "current_price",
            sa.Float(),
            nullable=False,
        ),
        sa.Column(
            "position_value_usd",
            sa.Float(),
            nullable=False,
        ),
        sa.Column(
            "reserved_margin_usd",
            sa.Float(),
            nullable=False,
        ),
        sa.Column(
            "unrealized_pnl_usd",
            sa.Float(),
            nullable=False,
            server_default=sa.text("0"),
        ),
        sa.Column(
            "realized_pnl_usd",
            sa.Float(),
            nullable=False,
            server_default=sa.text("0"),
        ),
        sa.Column(
            "total_fees_usd",
            sa.Float(),
            nullable=False,
            server_default=sa.text("0"),
        ),
        sa.Column(
            "opened_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "closed_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.CheckConstraint(
            "quantity > 0",
            name=(
                "ck_paper_positions_"
                "quantity_positive"
            ),
        ),
        sa.CheckConstraint(
            "average_entry_price > 0",
            name=(
                "ck_paper_positions_"
                "entry_positive"
            ),
        ),
        sa.CheckConstraint(
            "current_price >= 0",
            name=(
                "ck_paper_positions_"
                "current_nonnegative"
            ),
        ),
        sa.CheckConstraint(
            "position_value_usd >= 0",
            name=(
                "ck_paper_positions_"
                "value_nonnegative"
            ),
        ),
        sa.CheckConstraint(
            "reserved_margin_usd >= 0",
            name=(
                "ck_paper_positions_"
                "margin_nonnegative"
            ),
        ),
        sa.CheckConstraint(
            "total_fees_usd >= 0",
            name=(
                "ck_paper_positions_"
                "fees_nonnegative"
            ),
        ),
    )
    op.create_index(
        "ix_paper_positions_account_status",
        "paper_trading_positions",
        [
            "paper_account_id",
            "status",
        ],
    )
    op.create_index(
        "ix_paper_positions_bot_symbol",
        "paper_trading_positions",
        [
            "trading_bot_id",
            "symbol",
        ],
    )
    op.create_table(
        "paper_trading_orders",
        sa.Column(
            "id",
            sa.Integer(),
            primary_key=True,
        ),
        sa.Column(
            "user_id",
            sa.Integer(),
            sa.ForeignKey(
                "users.id",
                ondelete="CASCADE",
            ),
            nullable=False,
        ),
        sa.Column(
            "trading_bot_id",
            sa.Integer(),
            sa.ForeignKey(
                "trading_bots.id",
                ondelete="CASCADE",
            ),
            nullable=False,
        ),
        sa.Column(
            "paper_account_id",
            sa.Integer(),
            sa.ForeignKey(
                "paper_trading_accounts.id",
                ondelete="CASCADE",
            ),
            nullable=False,
        ),
        sa.Column(
            "paper_position_id",
            sa.Integer(),
            sa.ForeignKey(
                "paper_trading_positions.id",
                ondelete="SET NULL",
            ),
            nullable=True,
        ),
        sa.Column(
            "symbol",
            sa.String(length=30),
            nullable=False,
        ),
        sa.Column(
            "category",
            sa.String(length=20),
            nullable=False,
        ),
        sa.Column(
            "side",
            sa.String(length=10),
            nullable=False,
        ),
        sa.Column(
            "position_effect",
            sa.String(length=20),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=False,
            server_default="FILLED",
        ),
        sa.Column(
            "quantity",
            sa.Float(),
            nullable=False,
        ),
        sa.Column(
            "reference_price",
            sa.Float(),
            nullable=False,
        ),
        sa.Column(
            "fill_price",
            sa.Float(),
            nullable=False,
        ),
        sa.Column(
            "gross_value_usd",
            sa.Float(),
            nullable=False,
        ),
        sa.Column(
            "fee_rate",
            sa.Float(),
            nullable=False,
        ),
        sa.Column(
            "fee_usd",
            sa.Float(),
            nullable=False,
        ),
        sa.Column(
            "slippage_rate",
            sa.Float(),
            nullable=False,
        ),
        sa.Column(
            "slippage_usd",
            sa.Float(),
            nullable=False,
        ),
        sa.Column(
            "realized_pnl_usd",
            sa.Float(),
            nullable=False,
            server_default=sa.text("0"),
        ),
        sa.Column(
            "decision_reason",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "filled_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.CheckConstraint(
            "quantity > 0",
            name=(
                "ck_paper_orders_"
                "quantity_positive"
            ),
        ),
        sa.CheckConstraint(
            "reference_price > 0",
            name=(
                "ck_paper_orders_"
                "reference_positive"
            ),
        ),
        sa.CheckConstraint(
            "fill_price > 0",
            name=(
                "ck_paper_orders_"
                "fill_positive"
            ),
        ),
        sa.CheckConstraint(
            "gross_value_usd > 0",
            name=(
                "ck_paper_orders_"
                "gross_positive"
            ),
        ),
        sa.CheckConstraint(
            "fee_rate >= 0",
            name=(
                "ck_paper_orders_"
                "fee_rate_nonnegative"
            ),
        ),
        sa.CheckConstraint(
            "fee_usd >= 0",
            name=(
                "ck_paper_orders_"
                "fee_nonnegative"
            ),
        ),
        sa.CheckConstraint(
            "slippage_rate >= 0",
            name=(
                "ck_paper_orders_"
                "slippage_rate_nonnegative"
            ),
        ),
        sa.CheckConstraint(
            "slippage_usd >= 0",
            name=(
                "ck_paper_orders_"
                "slippage_nonnegative"
            ),
        ),
    )
    op.create_index(
        "ix_paper_orders_account_created",
        "paper_trading_orders",
        [
            "paper_account_id",
            "created_at",
        ],
    )
    op.create_index(
        "ix_paper_orders_bot_symbol",
        "paper_trading_orders",
        [
            "trading_bot_id",
            "symbol",
        ],
    )
def downgrade() -> None:
    op.drop_index(
        "ix_paper_orders_bot_symbol",
        table_name="paper_trading_orders",
    )
    op.drop_index(
        "ix_paper_orders_account_created",
        table_name="paper_trading_orders",
    )
    op.drop_table(
        "paper_trading_orders"
    )
    op.drop_index(
        "ix_paper_positions_bot_symbol",
        table_name="paper_trading_positions",
    )
    op.drop_index(
        "ix_paper_positions_account_status",
        table_name="paper_trading_positions",
    )
    op.drop_table(
        "paper_trading_positions"
    )
    op.drop_index(
        "ix_paper_accounts_user_status",
        table_name="paper_trading_accounts",
    )
    op.drop_table(
        "paper_trading_accounts"
    )
