"""create strategy templates table
Revision ID: 13a0b1c2d3e4
Revises: 12f0a1b2c3d4
Create Date: 2026-07-22
"""
from collections.abc import (
    Sequence,
)
from alembic import (
    op,
)
import sqlalchemy as sa
revision: str = "13a0b1c2d3e4"
down_revision: str | None = (
    "12f0a1b2c3d4"
)
branch_labels: (
    str | Sequence[str] | None
) = None
depends_on: (
    str | Sequence[str] | None
) = None
def upgrade() -> None:
    op.create_table(
        "strategy_templates",
        sa.Column(
            "id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "user_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "name",
            sa.String(length=150),
            nullable=False,
        ),
        sa.Column(
            "description",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "strategy_type",
            sa.String(length=50),
            nullable=False,
        ),
        sa.Column(
            "symbol",
            sa.String(length=30),
            nullable=False,
        ),
        sa.Column(
            "category",
            sa.String(length=20),
            server_default="linear",
            nullable=False,
        ),
        sa.Column(
            "timeframe",
            sa.String(length=20),
            server_default="5m",
            nullable=False,
        ),
        sa.Column(
            "visibility",
            sa.String(length=20),
            server_default="PRIVATE",
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            server_default="DRAFT",
            nullable=False,
        ),
        sa.Column(
            "paper_trading",
            sa.Boolean(),
            server_default=sa.true(),
            nullable=False,
        ),
        sa.Column(
            "dry_run",
            sa.Boolean(),
            server_default=sa.true(),
            nullable=False,
        ),
        sa.Column(
            "risk_per_trade_percent",
            sa.Float(),
            server_default="1.0",
            nullable=False,
        ),
        sa.Column(
            "max_position_value_usd",
            sa.Float(),
            server_default="25.0",
            nullable=False,
        ),
        sa.Column(
            "max_daily_loss_percent",
            sa.Float(),
            server_default="3.0",
            nullable=False,
        ),
        sa.Column(
            "max_drawdown_percent",
            sa.Float(),
            server_default="10.0",
            nullable=False,
        ),
        sa.Column(
            "stop_loss_percent",
            sa.Float(),
            nullable=True,
        ),
        sa.Column(
            "take_profit_percent",
            sa.Float(),
            nullable=True,
        ),
        sa.Column(
            "strategy_config",
            sa.JSON(),
            server_default=sa.text(
                "'{}'"
            ),
            nullable=False,
        ),
        sa.Column(
            "version",
            sa.Integer(),
            server_default="1",
            nullable=False,
        ),
        sa.Column(
            "published_at",
            sa.DateTime(
                timezone=True
            ),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(
                timezone=True
            ),
            server_default=sa.text(
                "CURRENT_TIMESTAMP"
            ),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(
                timezone=True
            ),
            server_default=sa.text(
                "CURRENT_TIMESTAMP"
            ),
            nullable=False,
        ),
        sa.CheckConstraint(
            (
                "visibility IN "
                "('PRIVATE', 'PUBLIC')"
            ),
            name=(
                "ck_strategy_templates_"
                "visibility"
            ),
        ),
        sa.CheckConstraint(
            (
                "status IN "
                "('DRAFT', 'PUBLISHED', "
                "'ARCHIVED')"
            ),
            name=(
                "ck_strategy_templates_"
                "status"
            ),
        ),
        sa.CheckConstraint(
            "paper_trading OR dry_run",
            name=(
                "ck_strategy_templates_"
                "execution_safety"
            ),
        ),
        sa.CheckConstraint(
            "risk_per_trade_percent > 0",
            name=(
                "ck_strategy_templates_"
                "risk_positive"
            ),
        ),
        sa.CheckConstraint(
            "max_position_value_usd > 0",
            name=(
                "ck_strategy_templates_"
                "position_value_positive"
            ),
        ),
        sa.CheckConstraint(
            (
                "risk_per_trade_percent "
                "<= max_daily_loss_percent"
            ),
            name=(
                "ck_strategy_templates_"
                "risk_daily_loss"
            ),
        ),
        sa.CheckConstraint(
            (
                "max_daily_loss_percent "
                "<= max_drawdown_percent"
            ),
            name=(
                "ck_strategy_templates_"
                "daily_loss_drawdown"
            ),
        ),
        sa.CheckConstraint(
            (
                "stop_loss_percent IS NULL "
                "OR stop_loss_percent > 0"
            ),
            name=(
                "ck_strategy_templates_"
                "stop_loss_positive"
            ),
        ),
        sa.CheckConstraint(
            (
                "take_profit_percent IS NULL "
                "OR take_profit_percent > 0"
            ),
            name=(
                "ck_strategy_templates_"
                "take_profit_positive"
            ),
        ),
        sa.CheckConstraint(
            "version >= 1",
            name=(
                "ck_strategy_templates_"
                "version_positive"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id"
        ),
        sa.UniqueConstraint(
            "user_id",
            "name",
            name=(
                "uq_strategy_templates_"
                "user_name"
            ),
        ),
    )
    op.create_index(
        (
            "ix_strategy_templates_"
            "id"
        ),
        "strategy_templates",
        ["id"],
        unique=False,
    )
    op.create_index(
        (
            "ix_strategy_templates_"
            "user_id"
        ),
        "strategy_templates",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        (
            "ix_strategy_templates_"
            "strategy_type"
        ),
        "strategy_templates",
        ["strategy_type"],
        unique=False,
    )
    op.create_index(
        (
            "ix_strategy_templates_"
            "symbol"
        ),
        "strategy_templates",
        ["symbol"],
        unique=False,
    )
    op.create_index(
        (
            "ix_strategy_templates_"
            "timeframe"
        ),
        "strategy_templates",
        ["timeframe"],
        unique=False,
    )
    op.create_index(
        (
            "ix_strategy_templates_"
            "visibility"
        ),
        "strategy_templates",
        ["visibility"],
        unique=False,
    )
    op.create_index(
        (
            "ix_strategy_templates_"
            "status"
        ),
        "strategy_templates",
        ["status"],
        unique=False,
    )
    op.create_index(
        (
            "ix_strategy_templates_"
            "updated_at"
        ),
        "strategy_templates",
        ["updated_at"],
        unique=False,
    )
    op.create_index(
        (
            "ix_strategy_templates_"
            "user_status"
        ),
        "strategy_templates",
        [
            "user_id",
            "status",
        ],
        unique=False,
    )
    op.create_index(
        (
            "ix_strategy_templates_"
            "visibility_status"
        ),
        "strategy_templates",
        [
            "visibility",
            "status",
        ],
        unique=False,
    )
    op.create_index(
        (
            "ix_strategy_templates_"
            "user_updated"
        ),
        "strategy_templates",
        [
            "user_id",
            "updated_at",
        ],
        unique=False,
    )
def downgrade() -> None:
    op.drop_index(
        (
            "ix_strategy_templates_"
            "user_updated"
        ),
        table_name=(
            "strategy_templates"
        ),
    )
    op.drop_index(
        (
            "ix_strategy_templates_"
            "visibility_status"
        ),
        table_name=(
            "strategy_templates"
        ),
    )
    op.drop_index(
        (
            "ix_strategy_templates_"
            "user_status"
        ),
        table_name=(
            "strategy_templates"
        ),
    )
    op.drop_index(
        (
            "ix_strategy_templates_"
            "updated_at"
        ),
        table_name=(
            "strategy_templates"
        ),
    )
    op.drop_index(
        (
            "ix_strategy_templates_"
            "status"
        ),
        table_name=(
            "strategy_templates"
        ),
    )
    op.drop_index(
        (
            "ix_strategy_templates_"
            "visibility"
        ),
        table_name=(
            "strategy_templates"
        ),
    )
    op.drop_index(
        (
            "ix_strategy_templates_"
            "timeframe"
        ),
        table_name=(
            "strategy_templates"
        ),
    )
    op.drop_index(
        (
            "ix_strategy_templates_"
            "symbol"
        ),
        table_name=(
            "strategy_templates"
        ),
    )
    op.drop_index(
        (
            "ix_strategy_templates_"
            "strategy_type"
        ),
        table_name=(
            "strategy_templates"
        ),
    )
    op.drop_index(
        (
            "ix_strategy_templates_"
            "user_id"
        ),
        table_name=(
            "strategy_templates"
        ),
    )
    op.drop_index(
        (
            "ix_strategy_templates_"
            "id"
        ),
        table_name=(
            "strategy_templates"
        ),
    )
    op.drop_table(
        "strategy_templates"
    )
