"""create exchange accounts table

Revision ID: 6fc8c78a4927
Revises: 1ccc03150998
Create Date: 2026-07-07 21:07:20.459022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fc8c78a4927'
down_revision: Union[str, Sequence[str], None] = '1ccc03150998'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exchange_name', sa.String(length=50), nullable=False),
    sa.Column('account_name', sa.String(length=150), nullable=False),
    sa.Column('encrypted_api_key', sa.String(length=500), nullable=False),
    sa.Column('encrypted_api_secret', sa.String(length=500), nullable=False),
    sa.Column('is_testnet', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exchange_accounts_exchange_name'), 'exchange_accounts', ['exchange_name'], unique=False)
    op.create_index(op.f('ix_exchange_accounts_id'), 'exchange_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_exchange_accounts_user_id'), 'exchange_accounts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exchange_accounts_user_id'), table_name='exchange_accounts')
    op.drop_index(op.f('ix_exchange_accounts_id'), table_name='exchange_accounts')
    op.drop_index(op.f('ix_exchange_accounts_exchange_name'), table_name='exchange_accounts')
    op.drop_table('exchange_accounts')
    # ### end Alembic commands ###
