"""create portfolio synchronization snapshots table
Revision ID: 7a1f0c2d9e44
Revises: 6fc8c78a4927
Create Date: 2026-07-18 21:30:00.000000
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
revision: str = "7a1f0c2d9e44"
down_revision: Union[
    str,
    Sequence[str],
    None,
] = "6fc8c78a4927"
branch_labels: Union[
    str,
    Sequence[str],
    None,
] = None
depends_on: Union[
    str,
    Sequence[str],
    None,
] = None
def upgrade() -> None:
    op.create_table(
        "portfolio_sync_snapshots",
        sa.Column(
            "id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "user_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "portfolio_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "exchange_account_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "exchange_name",
            sa.String(length=50),
            nullable=False,
        ),
        sa.Column(
            "account_type",
            sa.String(length=30),
            nullable=False,
        ),
        sa.Column(
            "category",
            sa.String(length=20),
            nullable=False,
        ),
        sa.Column(
            "settle_coin",
            sa.String(length=20),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=False,
        ),
        sa.Column(
            "fingerprint",
            sa.String(length=64),
            nullable=False,
        ),
        sa.Column(
            "sync_version",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "total_equity_usd",
            sa.Float(),
            nullable=False,
        ),
        sa.Column(
            "total_wallet_balance_usd",
            sa.Float(),
            nullable=False,
        ),
        sa.Column(
            "total_available_balance_usd",
            sa.Float(),
            nullable=False,
        ),
        sa.Column(
            "total_unrealized_pnl_usd",
            sa.Float(),
            nullable=False,
        ),
        sa.Column(
            "total_realized_pnl_usd",
            sa.Float(),
            nullable=False,
        ),
        sa.Column(
            "total_position_value_usd",
            sa.Float(),
            nullable=False,
        ),
        sa.Column(
            "coin_count",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "open_position_count",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "open_order_count",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "balance_payload",
            sa.JSON(),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "positions_payload",
            sa.JSON(),
            server_default=sa.text("'[]'"),
            nullable=False,
        ),
        sa.Column(
            "orders_payload",
            sa.JSON(),
            server_default=sa.text("'[]'"),
            nullable=False,
        ),
        sa.Column(
            "error_message",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "synced_at",
            sa.DateTime(timezone=True),
            server_default=sa.text(
                "(CURRENT_TIMESTAMP)"
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text(
                "(CURRENT_TIMESTAMP)"
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["exchange_account_id"],
            ["exchange_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["portfolios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "portfolio_id",
            "exchange_account_id",
            "fingerprint",
            name=(
                "uq_portfolio_sync_snapshot_"
                "fingerprint"
            ),
        ),
    )
    op.create_index(
        op.f(
            "ix_portfolio_sync_snapshots_id"
        ),
        "portfolio_sync_snapshots",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f(
            "ix_portfolio_sync_snapshots_user_id"
        ),
        "portfolio_sync_snapshots",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f(
            "ix_portfolio_sync_snapshots_"
            "portfolio_id"
        ),
        "portfolio_sync_snapshots",
        ["portfolio_id"],
        unique=False,
    )
    op.create_index(
        op.f(
            "ix_portfolio_sync_snapshots_"
            "exchange_account_id"
        ),
        "portfolio_sync_snapshots",
        ["exchange_account_id"],
        unique=False,
    )
    op.create_index(
        op.f(
            "ix_portfolio_sync_snapshots_"
            "exchange_name"
        ),
        "portfolio_sync_snapshots",
        ["exchange_name"],
        unique=False,
    )
    op.create_index(
        op.f(
            "ix_portfolio_sync_snapshots_status"
        ),
        "portfolio_sync_snapshots",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f(
            "ix_portfolio_sync_snapshots_"
            "synced_at"
        ),
        "portfolio_sync_snapshots",
        ["synced_at"],
        unique=False,
    )
def downgrade() -> None:
    op.drop_index(
        op.f(
            "ix_portfolio_sync_snapshots_"
            "synced_at"
        ),
        table_name="portfolio_sync_snapshots",
    )
    op.drop_index(
        op.f(
            "ix_portfolio_sync_snapshots_status"
        ),
        table_name="portfolio_sync_snapshots",
    )
    op.drop_index(
        op.f(
            "ix_portfolio_sync_snapshots_"
            "exchange_name"
        ),
        table_name="portfolio_sync_snapshots",
    )
    op.drop_index(
        op.f(
            "ix_portfolio_sync_snapshots_"
            "exchange_account_id"
        ),
        table_name="portfolio_sync_snapshots",
    )
    op.drop_index(
        op.f(
            "ix_portfolio_sync_snapshots_"
            "portfolio_id"
        ),
        table_name="portfolio_sync_snapshots",
    )
    op.drop_index(
        op.f(
            "ix_portfolio_sync_snapshots_user_id"
        ),
        table_name="portfolio_sync_snapshots",
    )
    op.drop_index(
        op.f(
            "ix_portfolio_sync_snapshots_id"
        ),
        table_name="portfolio_sync_snapshots",
    )
    op.drop_table("portfolio_sync_snapshots")
